apiVersion: batch/v1
kind: CronJob
metadata:
  name: latency-aggregator
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.aggregator.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: aggregator
              image: {{ .Values.aggregator.image }}
              command: ["python", "/aggregator/aggregator.py"]
              volumeMounts:
                - mountPath: /latency
                  name: latencystore
          volumes:
            - name: latencystore
              persistentVolumeClaim:
                claimName: {{ .Values.latencyPVC.name }}