# DaemonSet RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: latency-measure-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: latency-measure-role
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: latency-measure-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: latency-measure-role
subjects:
- kind: ServiceAccount
  name: latency-measure-sa
  namespace: {{ .Values.namespace }}
---
# Scheduler RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-latency-scheduler-sa
  namespace: {{ .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-latency-scheduler-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/binding"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-latency-scheduler-rolebinding
subjects:
- kind: ServiceAccount
  name: my-latency-scheduler-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: my-latency-scheduler-role