apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-latency-scheduler
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.scheduler.replicas }}
  selector:
    matchLabels:
      app: my-latency-scheduler
  template:
    metadata:
      labels:
        app: my-latency-scheduler
    spec:
      serviceAccountName: my-latency-scheduler-sa
      containers:
        - name: scheduler
          image: {{ .Values.scheduler.image }}
          volumeMounts:
            - name: latencystore
              mountPath: /latency
      volumes:
        - name: latencystore
          persistentVolumeClaim:
            claimName: {{ .Values.latencyPVC.name }}