apiVersion: v1
kind: Pod
metadata:
  name: latency-debug
  namespace: kube-system
spec:
  containers:
    - name: debug
      image: busybox
      command: ["sleep", "10000"]
      volumeMounts:
        - name: latencystore
          mountPath: /latency
  volumes:
    - name: latencystore
      persistentVolumeClaim:
        claimName: latency-pvc
  restartPolicy: Never
