apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: latency-measure
  namespace: kube-system
  labels:
    app: latency-measure
spec:
  selector:
    matchLabels:
      app: latency-measure
  template:
    metadata:
      labels:
        app: latency-measure
    spec:
      serviceAccountName: latency-measure-sa  # <<<<<< KEY LINE
      containers:
      - name: measure
        image: IMAGE_PLACEHOLDER
        env:
        - name: SLEEP_INTERVAL
          value: "60"
        - name: PING_COUNT
          value: "4"
        - name: PING_TIMEOUT
          value: "15"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
        volumeMounts:
        - name: latencystore
          mountPath: /latency
      volumes:
      - name: latencystore
        emptyDir: {}
      restartPolicy: Always
