apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-latency-scheduler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-latency-scheduler
  template:
    metadata:
      labels:
        app: my-latency-scheduler
    spec:
      serviceAccountName: my-latency-scheduler-sa
      containers:
      - name: scheduler
        image: sanjeevkrmenon/latent-scheduler:scheduler1
        # The scheduler binary expects the latency JSON available at /latency
        volumeMounts:
        - name: latencystore
          mountPath: /latency
      volumes:
      - name: latencystore
        emptyDir: {}    # (for dev only, in prod use NFS or other shared storage)