apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: latency-measure
  namespace: latency-scheduler
spec:
  selector:
    matchLabels:
      app: latency-measure
  template:
    metadata:
      labels:
        app: latency-measure
    spec:
      serviceAccountName: latency-measure-sa
      containers:
        - name: measure
          image: sanjeevkrmenon/latency-measure:latest
          volumeMounts:
            - mountPath: /latency
              name: latencystore
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
        - name: latencystore
          persistentVolumeClaim:
            claimName: latency-pvc