apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-latency-scheduler-sa
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: my-latency-scheduler-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/binding"]
    verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-latency-scheduler-rolebinding
subjects:
  - kind: ServiceAccount
    name: my-latency-scheduler-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: my-latency-scheduler-role
  apiGroup: rbac.authorization.k8s.io