apiVersion: v1
kind: PersistentVolume
metadata:
  name: latency-nfs-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-service.nfs-test.svc.cluster.local
    path: /nfsshare
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: latency-pvc
  namespace: latency-scheduler
spec:
  storageClassName: ""           # must match the 'none' of static PV!
  volumeName: latency-nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi